Description: >
  Author - DeVesco Pierre
  Project - Udacity DevOps Capstone Project
  Creates the Kubernetes Repository for the capstone project.

Parameters:
  ProjectName:
    Description: An project Name that will be prefixed to resoure names
    Type: String

Resources:
  ProjectRepository:
    Type: AWS::ECR::Repository 
    Properties:
      ImageScanningConfiguration:
        scanOnPush: true
      RepositoryName: !Sub '${ProjectName}'
Outputs:
  Repository:
    Value: !GetAtt ProjectRepository.Arn 