apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-ENVIRONMENT
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone-app-ENVIRONMENT
        image: IMAGE
        imagePullPolicy: Always
        ports:
          - containerPort: 80