apiVersion: v1
kind: Service
metadata:
  name: capstone-app-ENVIRONMENT
  namespace: ENVIRONMENT
  labels:
    app: capstone
    service.kubernetes.io/name: capstone
    service.kubernetes.io/environment: ENVIRONMENT
spec:
  type: LoadBalancer
  selector: 
    app: capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
